# Generated by Django 6.0.1 on 2026-01-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='points_for_delivery',
            field=models.ManyToManyField(blank=True, null=True, related_name='delivery_point_routes', to='routes.deliverypoint'),
        ),
    ]
