# Generated by Django 6.0.1 on 2026-01-23 10:34

import django.core.validators
import drivers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(validators=[drivers.validators.driver_years_validator])),
                ('phone_number', models.CharField(max_length=10)),
                ('driving_license_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{10}$', 'Driving Licence must contain exactly 10 uppercase alphanumeric characters')])),
                ('years_of_experience', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
